cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
url(r'^$', views.cart_detail, name='cart_detail'),
url(r'^add/(?P<product_id>\d+)/$',
views.cart_add,
name='cart_add'),
url(r'^remove/(?P<product_id>\d+)/$',
views.cart_remove,
name='cart_remove'),
]

myshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^', include('shop.urls', namespace='shop')),

]

# urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  

shop/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
url(r'^$', views.product_list, name='product_list'),
url(r'^(?P<category_slug>[-\w]+)/$',
views.product_list,
name='product_list_by_category'),
url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
views.product_detail,
name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length = 200 , db_index = True)
    slug = models.SlugField(max_length = 200 , db_index = True , unique = True)
    objects = models.Manager()

    class Meta:
        ordering = ('name' , )
        verbose_name = 'category'
        verbose_name_plural = 'categories'


    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse("shop:product_list_by_category", args=[self.slug])
    

class Product(models.Model):
    category = models.ForeignKey(Category , related_name = 'products')
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length =200 , db_index = True , unique = True)
    image = models.ImageField(upload_to = 'products/%Y/%m/%d' , blank=True)
    description = models.TextField(blank = True)
    price = models.DecimalField(max_digits = 10 , decimal_places = 2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()

    class Meta:
        ordering = ('name' , )
        index_together = (('id' , 'slug') , )


    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("shop:product_detail", args=[self.id , self.slug])



    

cart/forms.py
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    update = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)
    

cart/views.py
from django.shortcuts import render

# Create your views here.

from shop.recommender import Recommender
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
import redis

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
        quantity=cd['quantity'],
        update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)

    r = Recommender()
    cart_products = [item['product'] for item in cart]
    r.products_bought([item['product'] for item in cart])

    recommended_products = r.suggest_products_for(cart_products , max_results = 4)
    return render(request, 'cart/details.html', {'cart': cart , 'recommended_products': recommended_products})

shop/views.py
from django.shortcuts import render, get_object_or_404
# Create your views here.
from django.http import HttpResponse
from .recommender import Recommender
from cart.forms import CartAddProductForm
from .models import Category,Product
#Creates a list view to display all the products or filter them with category
def product_list(request , category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available = True)

    if category_slug:
        category = get_object_or_404(Category , slug = category_slug)
        products = products.filter(category = category)

    return render(request , 'shop/product/events.html' , {'category':category , 'categories':categories , 'products':products})


#Creates a detail view to display all the particular product based on 
def product_detail(request , id , slug):
    product = get_object_or_404(Product , id=id , slug=slug , available = True)

    cart_product_form = CartAddProductForm()

    r = Recommender()
    recommended_products = r.suggest_products_for([product] , 4)

    
    return render(request , 'shop/product/details.html' , {'product':product , 'cart_product_form':cart_product_form , 'recommended_products': recommended_products })

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Your shopping cart
{% endblock %}
{% block content %}
<h1>Your shopping cart</h1>
<table class="cart">
<thead>
<tr>
<th>Image</th>


<th>Product</th>
<th>Quantity</th>
<th>Remove</th>
<th>Unit price</th>
<th>Price</th>
</tr>
</thead>
<tbody>
{% for item in cart %}
{% with product=item.product %}
<tr>
<td>
<a href="{{ product.get_absolute_url }}">
<img src="{% if product.image %}{{ product.image.url
}}{% else %}{% static "img/no_image.png" %}{% endif %}">
</a>
</td>
<td>{{ product.name }}</td>
<td>{{ item.quantity }}</td>
<td><a href="{% url "cart:cart_remove" product.id %}">Remove</a></td>
<td class="num">${{ item.price }}</td>
<td class="num">${{ item.total_price }}</td>
</tr>
{% endwith %}
{% endfor %}
<tr class="total">
<td>Total</td>
<td colspan="4"></td>
<td class="num">${{ cart.get_total_price }}</td>
</tr>
</tbody>
</table>

{% if recommended_products %}
<div class="recommendations cart">
<h3>People who bought this also bought</h3>
{% for p in recommended_products %}
<div class="item">
<a href="{{ p.get_absolute_url }}">
<img src="{% if p.image %}{{ p.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
</a>
<p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
</div>
{% endfor %}
</div>
{% endif %}


<p class="text-right">
<a href="{% url "shop:product_list" %}" class="button
light">Continue shopping</a>
<a href="#" class="button">Checkout</a>
</p>
{% endblock %}

cart/templates/cart/details.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="shortcut icon" href="img/fav.png">

<meta name="author" content="CodePixar">

<meta name="description" content="">

<meta name="keywords" content="">

<meta charset="UTF-8">

<title>Karma Shop</title>

<link rel="stylesheet" href="https://colorlib.com/preview/theme/karma/css/linearicons.css">
<link rel="stylesheet" href="https://colorlib.com/preview/theme/karma/css/owl.carousel.css">
<link rel="stylesheet" href="https://colorlib.com/preview/theme/karma/css/font-awesome.min.css">
<link rel="stylesheet" href="https://colorlib.com/preview/theme/karma/css/themify-icons.css">
<link rel="stylesheet" href="https://colorlib.com/preview/theme/karma/css/nice-select.css">
<link rel="stylesheet" href="https://colorlib.com/preview/theme/karma/css/nouislider.min.css">
<link rel="stylesheet" href="https://colorlib.com/preview/theme/karma/css/bootstrap.css">
<link rel="stylesheet" href="https://colorlib.com/preview/theme/karma/css/main.css">
<link rel="stylesheet" href="{% static 'css/33.css' %}">
    <link rel="stylesheet" href="{% static 'css/34.css' %}">
    <link rel="shortcut icon" type="image/png" href="img/favicon.png" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <!--    <link href="css/bootstrap.min.css" rel="stylesheet">-->
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/35.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/36.css' %}" rel="stylesheet">
    <link href="{% static 'css/37.css' %}" rel="stylesheet">

    <link href="{% static 'css/38.css' %}" rel="stylesheet">

    <link href="{% static 'css/39.css' %}" rel="stylesheet">
    <link href="{% static 'css/40.css' %}" rel="stylesheet">
    <link href="{% static 'css/41.css' %}" rel="stylesheet">
    <link href="{% static 'css/42.css' %}" rel="stylesheet">
    <link href="{% static 'css/43.css' %}" rel="stylesheet">
    <link href="{% static 'css/82.css' %}" rel="stylesheet">

</head>


<body>

<header class="header_area sticky-header">
{% comment %} <div class="main_menu">
<nav class="navbar navbar-expand-lg navbar-light main_box">
<div class="container">

<a class="navbar-brand logo_h" href="index.html"><img src="img/logo.png" alt=""></a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>

<div class="collapse navbar-collapse offset" id="navbarSupportedContent">
<ul class="nav navbar-nav menu_nav ml-auto">
<li class="nav-item"><a class="nav-link" href="index.html">Home</a></li>
<li class="nav-item submenu dropdown active">
<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Shop</a>
<ul class="dropdown-menu">
<li class="nav-item"><a class="nav-link" href="category.html">Shop Category</a></li>
<li class="nav-item"><a class="nav-link" href="single-product.html">Product Details</a></li>
<li class="nav-item"><a class="nav-link" href="checkout.html">Product Checkout</a></li>
<li class="nav-item active"><a class="nav-link" href="cart.html">Shopping Cart</a></li>
<li class="nav-item"><a class="nav-link" href="confirmation.html">Confirmation</a></li>
</ul>
</li>
<li class="nav-item submenu dropdown">
<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Blog</a>
<ul class="dropdown-menu">
<li class="nav-item"><a class="nav-link" href="blog.html">Blog</a></li>
<li class="nav-item"><a class="nav-link" href="single-blog.html">Blog Details</a></li>
</ul>
</li>
<li class="nav-item submenu dropdown">
<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Pages</a>
<ul class="dropdown-menu">
<li class="nav-item"><a class="nav-link" href="login.html">Login</a></li>
<li class="nav-item"><a class="nav-link" href="tracking.html">Tracking</a></li>
<li class="nav-item"><a class="nav-link" href="elements.html">Elements</a></li>
</ul>
</li>
<li class="nav-item"><a class="nav-link" href="contact.html">Contact</a></li>
</ul>
<ul class="nav navbar-nav navbar-right">
<li class="nav-item"><a href="#" class="cart"><span class="ti-bag"></span></a></li>
<li class="nav-item">
<button class="search"><span class="lnr lnr-magnifier" id="search"></span></button>
</li>
</ul>
</div>
</div>
</nav>
</div>
<div class="search_input" id="search_input_box">
<div class="container">
<form class="d-flex justify-content-between">
<input type="text" class="form-control" id="search_input" placeholder="Search Here">
<button type="submit" class="btn"></button>
<span class="lnr lnr-cross" id="close_search" title="Close Search"></span>
</form>
</div>
</div> {% endcomment %}
</header>


<section class="banner-area organic-breadcrumb">
<div class="container">
<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
<div class="col-first">
<h1>Shopping Cart</h1>
<nav class="d-flex align-items-center">
<a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
<a href="category.html">Cart</a>
</nav>
</div>
</div>
</div>
</section>


<section class="cart_area">
<div class="container">
<div class="cart_inner">
<div class="table-responsive">
<table class="table">
<thead>
<tr>
<th scope="col">Product</th>
<th scope="col">Quantity</th>
<th scope="col">Remove</th>
<th scope="col">Unit Price</th>
<th scope="col">Price</th>
</tr>
</thead>


<tbody>
{% for item in cart %}
{% with product=item.product %}
<tr>
<td>
<div class="media">
<div class="d-flex">
{% comment %} <img src="{{ product.image.url }}" alt=""> {% endcomment %}
</div>
<div class="media-body">
<p>{{ product.name }}</p>
</div>
</div>
</td>
<td>
<h5>{{ item.quantity }}</h5>
</td>

<td>
<a href="{% url "cart:cart_remove" product.id %}">Remove</a></td>
<td>
<h5>Rs.{{ item.price }}</h5>
</td>
<td>
<h5>Rs.{{ item.total_price }}</h5>
</td>
</tr>

{% endwith %}
{% endfor %}
<tr>
<td></td><td></td>
<td></td>
<td></td>

<td>
<h5>Rs.{{ cart.get_total_price }}</h5>
</td>
</tr>


</tbody>
</table>


</div>
</div>
</div>
</section>

<div class="row">
						{% for p in recommended_products %}

                        <div class="col-4">
<div class="card profile-card-2 toggle">
                                <div class="card-img-block">
                                   <a href="{{ product.get_absolute_url }}"> <img class="img-fluid" src="https://images.pexels.com/photos/870903/pexels-photo-870903.jpeg?w=940&h=650&auto=compress&cs=tinysrgb" alt="Card image cap"></a>
                                </div>
                                <div class="card-body pt-5">
                                    {% comment %} <img src="https://randomuser.me/api/portraits/men/64.jpg" alt="profile-image" class="profile" /> {% endcomment %}
                                    <h5 class="card-title">{{ p.name }}</h5>
                                    <h5 class="card-title">{{ p.price }}</h5>

                                    <p class="card-text">{{p.description|truncatechars:20}}</p>
                                    <div class="icon-block"><a href="#"><i class="fa fa-facebook"></i></a><a href="#"> <i class="fa fa-twitter"></i></a><a href="#"> <i class="fa fa-google-plus"></i></a>
                                        <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><button class="button" data-toggle="modal" data-target="#modal-info"><a href="{{ p.get_absolute_url }}">CHECK NOW</button></div>
                                </div>
                            </div>


                        </div>
                        
                                          
  

{% endfor %}
<br><br>
</div>

							
<footer class="footer-area section_gap">


</footer>

<script src="js/vendor/jquery-2.2.4.min.js" type="cf91b4856fcba0b503a2bb8d-text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous" type="cf91b4856fcba0b503a2bb8d-text/javascript"></script>
<script src="js/vendor/bootstrap.min.js" type="cf91b4856fcba0b503a2bb8d-text/javascript"></script>
<script src="js/jquery.ajaxchimp.min.js" type="cf91b4856fcba0b503a2bb8d-text/javascript"></script>
<script src="js/jquery.nice-select.min.js" type="cf91b4856fcba0b503a2bb8d-text/javascript"></script>
<script src="js/jquery.sticky.js" type="cf91b4856fcba0b503a2bb8d-text/javascript"></script>
<script src="js/nouislider.min.js" type="cf91b4856fcba0b503a2bb8d-text/javascript"></script>
<script src="js/jquery.magnific-popup.min.js" type="cf91b4856fcba0b503a2bb8d-text/javascript"></script>
<script src="js/owl.carousel.min.js" type="cf91b4856fcba0b503a2bb8d-text/javascript"></script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE" type="cf91b4856fcba0b503a2bb8d-text/javascript"></script>
<script src="js/gmaps.min.js" type="cf91b4856fcba0b503a2bb8d-text/javascript"></script>
<script src="js/main.js" type="cf91b4856fcba0b503a2bb8d-text/javascript"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13" type="cf91b4856fcba0b503a2bb8d-text/javascript"></script>
<script type="cf91b4856fcba0b503a2bb8d-text/javascript">
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>
<script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js" data-cf-settings="cf91b4856fcba0b503a2bb8d-|49" defer=""></script></body>
</html>

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>{% block title %}My shop{% endblock %}</title>
<link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
<div id="header">
<a href="/" class="logo">My shop</a>
</div>
<div id="subheader">
    <div class="cart">
        {% with total_items=cart|length %}
        {% if cart|length > 0 %}
        Your cart:
        <a href="{% url "cart:cart_detail" %}">
        {{ total_items }} item{{ total_items|pluralize }},
        ${{ cart.get_total_price }}
        </a>
        {% else %}
        Your cart is empty.
        {% endif %}
        {% endwith %}
        </div>
</div>
<div id="content">
{% block content %}
{% endblock %}
</div>
</body>
</html>

shop/templates/shop/product/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
<div class="product-detail">
<img src="{% if product.image %}{{ product.image.url }}{% else %}
{% static "img/no_image.png" %}{% endif %}">
<h1>{{ product.name }}</h1>
<h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
<p class="price">${{ product.price }}</p>
<form action="{% url "cart:cart_add" product.id %}" method="post">
{{ cart_product_form }}
{% csrf_token %}
<input type="submit" value="Add to cart">
</form>


{{ product.description|linebreaks }}

{% if recommended_products %}
<div class="recommendations">
<h3>People who bought this also bought</h3>
{% for p in recommended_products %}
<div class="item">
<a href="{{ p.get_absolute_url }}">
<img src="{% if p.image %}{{ p.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
</a>
<p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
</div>
{% endfor %}
</div>
{% endif %}

</div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
<div id="sidebar">
<h3>Categories</h3>
<ul>
    <li {% if not category %} class="selected" {% endif %}>
        <a href="{% url 'shop:product_list' %}">All</a>
        </li>
        {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
        <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
        {% endfor %}
        </ul>
        </div>
        <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
        {% for product in products %}
        <div class="item">
        <a href="{{ product.get_absolute_url }}">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
        ${{ product.price }}
        </div>
        {% endfor %}
        </div>
        {% endblock %}